### ISSUE TITLE
Oracle Daemon, Contract, Beacon, PoW synchronization and validation spec

### ISSUE THREAD

**Issue by ongrid** [lidofinance/lido-improvement-proposals#4]
* The deterministic algorithm for oracle daemons synchronization should be formally specified
* Validation: the oracle contract should implement protection against incorrect values from oracle daemons

Proposed and discussed on the calls and follow-ups
* algorithm how to find exact checkpoints for both chains to retrieve states from
* limits like `maxBalanceChange per epoch`
* reportable epoch validation

**Comment by vshvsh** [comment]
Closed by #3
